<?php $helper = Mage::helper("loyalty"); ?>
<?php if($helper->isActive()): ?>
    <?php
        $minValToUsePoints = $helper->getMinValToUsePoints();
        $customer = Mage::getSingleton('customer/session')->getCustomer();
        $quote = Mage::getSingleton('checkout/session')->getQuote();
        $grandTotal = $quote->getGrandTotal();
        $subTotal = $quote->getSubtotal();
        $points = Mage::getModel("loyalty/points")->getAvailablePoints();
        $discount = $helper->calcDiscount($points);
        $_code = $this->getMethodCode();        
        $hasPixDiscount = false;
        $appliedRuleIds = $quote->getAppliedRuleIds();
        $_pixRuleId = Mage::app()->getStore()->getConfig("catalog/pixdiscount/ruleid");
        if ($appliedRuleIds == $_pixRuleId) {
            $hasPixDiscount = true;
        } else {
            $hasPixDiscount = false;
        }
    ?>
    <div class="checkout-loyalty-container">
        <?php if($subTotal < $minValToUsePoints): ?>
            <script> // Remove a forma de pagamento e não mostra o desconto
                jQuery("#checkout-payment-method-load .payment-type.loyalty dt").remove();
            </script>
            <?php elseif(
                (($discount >= $grandTotal) && (empty($hasPixDiscount) && !$helper->hasLoyaltyDiscountApplied()))
                 || 
                ($discount >= ($quote->getSubtotal() + $quote->getShippingAddress()->getShippingAmount()) && !$helper->hasLoyaltyDiscountApplied())
            ): ?>
            <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none;">
                <li>
                    
                    <?php if(!empty(Mage::getStoreConfig('loyalty/advanced/show_points'))): ?>
                        <p>
                            Você tem <span class="my-points"><?php echo $points; ?> pontos</span> para serem utilizados, ou seja, <span class="my-discount"><?php echo Mage::helper('core')->currency($discount, true, false); ?></span> de desconto em seus pedidos<br> Ao selecionar essa opção, você irá pagar o seu <span class="bold">pedido por completo</span> usando apenas os seus pontos <br>
                        </p>
                    <?php else: ?>
                        <p>
                            Você tem <span class="my-discount"><?php echo Mage::helper('core')->currency($discount, true, false); ?></span> de crédito para usar usado como desconto em seus pedidos.<br> Ao selecionar essa opção, você irá usá-los para pagar o seu <span class="bold">pedido por completo</span><br>
                        </p>
                    <?php endif; ?>
                </li>
            </ul>
        <?php else: ?>
            <script> // Remove a forma de pagamento e mostra o desconto
                jQuery("#checkout-payment-method-load .payment-type.loyalty dt").remove();
            </script>
            
            <?php if($points > 0): ?>

                <?php $boxClass = ""; ?>
                <?php if($helper->hasLoyaltyDiscountApplied()): ?>
                    <?php $boxClass = "active"; ?>
                <?php endif; ?>


                <div id="apply_loyalty_discount" class="has-points-to-use-box <?php echo $boxClass; ?>">
                    <div class="box-header">
                        <div class="box-checkbox"></div>
                        <?php if(!empty(Mage::getStoreConfig('loyalty/advanced/show_points'))): ?>
                            <h4>Usar meus pontos como desconto</h4>
                        <?php else: ?>
                            <h4>Usar meu crédito como desconto</h4>
                        <?php endif; ?>
                    </div>
                    <div class="box-content">
                        <?php if(!empty(Mage::getStoreConfig('loyalty/advanced/show_points'))): ?>
                            <p>Você tem <span class="my-points"><?php echo $points; ?> pontos</span>, ou seja <span class="my-discount"><?php echo Mage::helper('core')->currency($discount, true, false); ?></span> de desconto, clique aqui para aplicar</p>
                        <?php else: ?>
                            <p>Você tem <span class="my-discount"><?php echo Mage::helper('core')->currency($discount, true, false); ?></span> de crédito, clique aqui para aplicar</p>
                        <?php endif; ?>
                    </div>
                </div>

                <script>




                    function setLoyaltyCookie(name, value, minutes) {
                        var d = new Date;
                        d.setTime(d.getTime() + (minutes * 60 * 1000));
                        document.cookie = name + "=" + value + ";path=/;expires=" + d.toGMTString();
                    }

                    function getLoyaltyCookie(name) {
                        var v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
                        return v ? v[2] : null;
                    }


                    jQuery("#apply_loyalty_discount").on("click", function(e) {
                        e.preventDefault();
                        var box = jQuery(this);
                        
                        if(box.hasClass("active")) {
                            var action = "disable";
                            box.removeClass("active");
                        } else {
                            var action = "enable";
                            box.addClass("active");
                        }

                        // Add loading
                        jQuery("#onestepcheckout-payment-method").append("<div class='onestepcheckout-overlay onestepcheckout-overlay-48'></div>");

                        jQuery.ajax({
                            method: "POST",
                            url: "/loyalty/payment/apply",
                            data: { action: action, discount: <?php echo $discount; ?> }
                        })
                        .done(function(data) {
                            OSCPayment.forcesavePayment();
                            OSCShipment.switchToMethod(OSCShipment.currentMethod, true);
                            data = jQuery.parseJSON(data);
                            console.log(data.message);
                        });
                    });

                    // Verifica se o discount é maior que o grandtotal caso tenha desconto já aplicado, desaplica o desconto
                    <?php if($discount >= ($grandTotal + $discount)): ?>
                        console.log('<?php echo $grandTotal; ?>');
                        jQuery(document).ready(function($) {
                            if ($("#apply_loyalty_discount").hasClass("active")) {
                                jQuery("#apply_loyalty_discount").trigger("click");
                            }
                        });
                    <?php endif; ?>

                    // Verifica se é o primeiro acesso no checkout e marca a opção para usar desconto sozinho
                    setTimeout(function() {
                        var firstTime = getLoyaltyCookie("loyalty_first_time");
                        if(firstTime == "true" || firstTime == "" || firstTime == null) {
                            console.log("applicou o desconto automatico");
                            setLoyaltyCookie("loyalty_first_time", "false", 30);
                            jQuery("#apply_loyalty_discount").trigger("click");
                        }
                    }, 1000);
                    
                </script>


            <?php endif; ?>

        <?php endif; ?>
    </div>
<?php endif; ?>